--
-- mimic installer
--
-- Downloads mimic onto a ComputerCraft computer.
--
--   wget run <base-url>/install.lua
--
-- Pass a base URL if you are hosting it yourself:
--
--   wget run http://192.168.1.10:8000/install.lua http://192.168.1.10:8000
--
-- CC:Tweaked blocks private/loopback addresses by default. To serve from your own
-- machine, allow them in the CC config (computercraft-server.toml):
--
--   [[http.rules]]
--   host = "127.0.0.1"
--   action = "allow"
--

local DEFAULT_BASE = "https://raw.githubusercontent.com/TomTTFB/mimic/main"

local base = ... or DEFAULT_BASE
base = base:gsub("/$", "")

-- every file mimic needs, generated by tools/manifest.sh
local FILES = {
    "initenv.lua",

    "graphics/core.lua",
    "graphics/element.lua",
    "graphics/events.lua",
    "graphics/flasher.lua",
    "graphics/themes.lua",
    "graphics/elements/AppMultiPane.lua",
    "graphics/elements/ColorMap.lua",
    "graphics/elements/DisplayBox.lua",
    "graphics/elements/Div.lua",
    "graphics/elements/ListBox.lua",
    "graphics/elements/MultiPane.lua",
    "graphics/elements/PipeNetwork.lua",
    "graphics/elements/Rectangle.lua",
    "graphics/elements/TextBox.lua",
    "graphics/elements/Tiling.lua",
    "graphics/elements/animations/Waiting.lua",
    "graphics/elements/controls/App.lua",
    "graphics/elements/controls/Checkbox.lua",
    "graphics/elements/controls/HazardButton.lua",
    "graphics/elements/controls/MultiButton.lua",
    "graphics/elements/controls/NumericSpinbox.lua",
    "graphics/elements/controls/PushButton.lua",
    "graphics/elements/controls/Radio2D.lua",
    "graphics/elements/controls/RadioButton.lua",
    "graphics/elements/controls/Sidebar.lua",
    "graphics/elements/controls/SwitchButton.lua",
    "graphics/elements/controls/TabBar.lua",
    "graphics/elements/form/NumberField.lua",
    "graphics/elements/form/TextField.lua",
    "graphics/elements/indicators/AlarmLight.lua",
    "graphics/elements/indicators/DataIndicator.lua",
    "graphics/elements/indicators/HorizontalBar.lua",
    "graphics/elements/indicators/IconIndicator.lua",
    "graphics/elements/indicators/IndicatorLight.lua",
    "graphics/elements/indicators/LED.lua",
    "graphics/elements/indicators/LEDPair.lua",
    "graphics/elements/indicators/PowerIndicator.lua",
    "graphics/elements/indicators/RGBLED.lua",
    "graphics/elements/indicators/SignalBar.lua",
    "graphics/elements/indicators/StateIndicator.lua",
    "graphics/elements/indicators/TriIndicatorLight.lua",
    "graphics/elements/indicators/VerticalBar.lua",

    "scada-common/log.lua",
    "scada-common/psil.lua",
    "scada-common/tcd.lua",
    "scada-common/util.lua",

    "mimic/init.lua",
    "mimic/style.lua",
    "mimic/elements.lua",
    "mimic/LEDList.lua",
    "mimic/Panel.lua",
    "mimic/Gauge.lua",
    "mimic/Trend.lua",
    "mimic/BarChart.lua",
    "mimic/Tabs.lua",
    "mimic/Row.lua",
    "mimic/Grid.lua",
    "mimic/Table.lua",
    "mimic/Dialog.lua",
    "mimic/Paginator.lua",

    "examples/hello.lua",
    "examples/front_panel.lua",
    "examples/front_panel2.lua",
    "examples/panel_tabs.lua",
    "examples/dashboard.lua",
    "examples/facility.lua",
    "examples/themes.lua",
    "examples/paginated.lua",
}

local function fail(msg)
    term.setTextColor(colors.red)
    print("")
    print(msg)
    term.setTextColor(colors.white)
    error("", 0)
end

if not http then
    fail("The HTTP API is disabled. Enable it in the CC:Tweaked config, or copy the\n" ..
         "files into the computer's folder by hand.")
end

term.setTextColor(colors.yellow)
print("mimic installer")
term.setTextColor(colors.lightGray)
print("from " .. base)
term.setTextColor(colors.white)
print("")

local ok_count, failed = 0, {}

for i = 1, #FILES do
    local path = FILES[i]
    local url = base .. "/" .. path

    term.write(string.format("[%2d/%2d] %s", i, #FILES, path))

    local res, err = http.get(url)
    if res then
        local dir = fs.getDir(path)
        if dir ~= "" and not fs.exists(dir) then fs.makeDir(dir) end

        local f = fs.open(path, "w")
        f.write(res.readAll())
        f.close()
        res.close()

        ok_count = ok_count + 1
        term.setTextColor(colors.green)
        print("  ok")
    else
        failed[#failed + 1] = path .. " (" .. tostring(err) .. ")"
        term.setTextColor(colors.red)
        print("  FAILED")
    end
    term.setTextColor(colors.white)
end

print("")

if #failed > 0 then
    term.setTextColor(colors.red)
    print(#failed .. " of " .. #FILES .. " files failed:")
    for i = 1, math.min(#failed, 5) do print("  " .. failed[i]) end
    term.setTextColor(colors.white)
    print("")
    print("Check the base URL and that CC's HTTP rules allow it.")
    return
end

term.setTextColor(colors.green)
print("Installed " .. ok_count .. " files.")
term.setTextColor(colors.white)
print("")
print("This must be an ADVANCED computer for color.")
print("")
print("Try:")
print("  examples/hello        -- the basics")
print("  examples/panel_tabs   -- tabbed front panel, fits this screen")
print("  examples/themes       -- switch and customize themes")
print("  examples/facility     -- panel here + dashboard on a monitor")
print("")
print("For the dashboard you need an ADVANCED MONITOR at")
print("least 8 blocks wide by 4 tall.")
